### PR TITLE
Fix code coverage reporting

### PR DESCRIPTION
**Pull request by ghost**
#### What does this PR do?
- It fixes the non-reporting of the code coverage

#### Description of Tasks to be completed?
- Installation of the `nyc` reporter to report the code coverage to coveralls.
- Removal of the pre-existing istanbul reporter

#### How should this be manually tested?
- Check out into the `fix/code-coverage-reporting` branch, run `npm install`, then run `npm test`, you will see the code coverage displayed in the console.
- Check the build on Travis, you should see that the coverage is now being reported.
- Coverage can be seen as one of the checks passed/failed when any `push` or `pull request` is made.

#### Any background context you want to provide?
- The istanbul reporter seems a bit more complicated to configure, the `nyc` reporter thus provides a cleaner and more straightforward process of reporting the test coverage.

#### What are the relevant pivotal tracker stories?
- [#153507272](https://www.pivotaltracker.com/story/show/153507272)

### CODE REVIEW

**Comment by knite51** [comment]
I ran npm test as requested on the fix/code-coverage-reporting branch. am getting 
> 'nyc' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ghost** [comment]
Did you run `npm install`?

I guess I must have forgotten to tell you that anytime there's more than one person committing to a particular repository, whenever one person is working, it is best practice to first run `npm install` or `npm i`. That command updates your local `node_modules` with extra dependencies the other person must have installed. Only after the `npm install` can you then run the test.

**Comment by knite51** [comment]
And that should done after switching to this new branch you created right?

**Comment by ghost** [comment]
Yes. Check `How should this be manually tested` for full info.

**Comment by knite51** [comment]
Another thing. when i ran npm install, it stopped halfway (usual error for administrator permission) but the  .nyc_output file is already on my files now and the test ran but i was wondering if its necessary to run npm install as administrator just to complete what was installing before?

**Comment by ghost** [comment]
Hmmm. I don't think it's necessary yet. You can check back out into develop. What I wanted you to establish is that the test works.

**Comment by ghost** [comment]
I will merge this now, and you can then update your local develop with it.

**Pull request merged**
