### PR TITLE
install babel on devDependencies

### PR DESCRIPTION
**Pull request by knite51**

### CODE REVIEW

**Comment by ghost** [comment]
I am curious as to why you decided this. :)

**Comment by knite51** [comment]
I was trying to resolve a pull-request conflict. The branch was a commit ahead of the develop. I tried merging but i got a conflict since the develop has more content than it did when i created the branch. So i decided to make the commit directly on the develop (I know its not conventional.). i installed the babel-cli directly on the develop to fix it.

**Comment by ghost** [comment]
Hmmm. You could have asked how to fix the merge conflict instead of working directly on develop.

**Comment by knite51** [comment]
My apologies. I was so focused on the problem that i didn't think to ask. I still want to merge the branch though. How should i go about fixing the problem?

**Pull request closed without merging**
